/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AboutPageContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'placeholder' : IDL.Bool,
});
export const VideoProject = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'video' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'visible' : IDL.Bool,
  'youtubeUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'tel' : IDL.Text,
  'email' : IDL.Text,
  'socialMedia' : IDL.Vec(SocialMediaLink),
});
export const Stats = IDL.Record({
  'videoViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalVisits' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addVideoProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVideoProject' : IDL.Func([IDL.Text], [], []),
  'getAboutPageContent' : IDL.Func([], [IDL.Opt(AboutPageContent)], ['query']),
  'getAllVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoOrder' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getVideoProject' : IDL.Func([IDL.Text], [IDL.Opt(VideoProject)], ['query']),
  'getVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
  'incrementTotalVisits' : IDL.Func([], [], []),
  'incrementVideoView' : IDL.Func([IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAboutPageContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'setContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(SocialMediaLink)],
      [],
      [],
    ),
  'toggleVideoVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'updateVideoOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateVideoProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AboutPageContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'placeholder' : IDL.Bool,
  });
  const VideoProject = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'video' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'visible' : IDL.Bool,
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'tel' : IDL.Text,
    'email' : IDL.Text,
    'socialMedia' : IDL.Vec(SocialMediaLink),
  });
  const Stats = IDL.Record({
    'videoViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalVisits' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addVideoProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVideoProject' : IDL.Func([IDL.Text], [], []),
    'getAboutPageContent' : IDL.Func(
        [],
        [IDL.Opt(AboutPageContent)],
        ['query'],
      ),
    'getAllVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoOrder' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getVideoProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoProject)],
        ['query'],
      ),
    'getVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
    'incrementTotalVisits' : IDL.Func([], [], []),
    'incrementVideoView' : IDL.Func([IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAboutPageContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'setContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(SocialMediaLink)],
        [],
        [],
      ),
    'toggleVideoVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'updateVideoOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateVideoProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };