/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutPageContent {
  'title' : string,
  'content' : string,
  'placeholder' : boolean,
}
export interface ContactInfo {
  'tel' : string,
  'email' : string,
  'socialMedia' : Array<SocialMediaLink>,
}
export type ExternalBlob = Uint8Array;
export interface SocialMediaLink { 'url' : string, 'platform' : string }
export interface Stats {
  'videoViews' : Array<[string, bigint]>,
  'totalVisits' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoProject {
  'id' : string,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'video' : [] | [ExternalBlob],
  'description' : string,
  'visible' : boolean,
  'youtubeUrl' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addVideoProject' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [string],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideoProject' : ActorMethod<[string], undefined>,
  'getAboutPageContent' : ActorMethod<[], [] | [AboutPageContent]>,
  'getAllVideoProjects' : ActorMethod<[], Array<VideoProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoOrder' : ActorMethod<[], Array<string>>,
  'getVideoProject' : ActorMethod<[string], [] | [VideoProject]>,
  'getVideoProjects' : ActorMethod<[], Array<VideoProject>>,
  'incrementTotalVisits' : ActorMethod<[], undefined>,
  'incrementVideoView' : ActorMethod<[string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAboutPageContent' : ActorMethod<[string, string, boolean], undefined>,
  'setContactInfo' : ActorMethod<
    [string, string, Array<SocialMediaLink>],
    undefined
  >,
  'toggleVideoVisibility' : ActorMethod<[string, boolean], undefined>,
  'updateThumbnail' : ActorMethod<[string, ExternalBlob], undefined>,
  'updateVideoOrder' : ActorMethod<[Array<string>], undefined>,
  'updateVideoProject' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];